language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install .
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then pip install black; fi;

script:
  - python -m pytest
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then black --check reference_graph tests examples setup.py; fi;
