language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

before_install:
  - pip install poetry
  - poetry --version

install:
  - poetry install

script:
  - poetry run mypy --version || true
  - poetry run black --version || true
  - poetry run python -m pytest --runslow
